name: CI Test
on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    name: Node.js ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [^22.22, ^24.15, ^26]
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node-version }}
      # https://github.com/tinylibs/tinyclip/blob/76448e0b9e4b13897a3a4ae19222f6c5b6ec1b8f/.github/workflows/main.yml#L34-L35
      - run: sudo apt-get update && sudo apt-get install -y xclip xvfb
      - run: npm install
      # https://github.com/sindresorhus/clipboardy/issues/63#issuecomment-676484369
      - run: xvfb-run -a npm test
